language: php

php:
  - 5.3
  - 5.4

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install
   
script: phpunit --configuration phpunit.xml.dist

notifications:
  email:
    - phansys@gmail.com
    
branches:
  only:
    - master
    - v2.0.0
